version: "3.4"

services:
  api:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    container_name: "portfolio-api"
    volumes:
      - "./:/usr/src/app"
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - mysql-db
    environment:
      - PORTFOLIO_DB_HOST=mysql-db
      - PORTFOLIO_DB_USER=root
      - PORTFOLIO_DB_SECRET=root
      - PORTFOLIO_DB=portfolio
  mysql-db:
    image: mariadb:10
    container_name: "portfolio-db"
    volumes:
      - ./compose/mysql-data:/var/lib/mysql
      - ./compose/mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portfolio
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
